# Generated by Django 4.0.4 on 2022-05-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=50)),
                ('Prezime', models.CharField(max_length=50)),
                ('Telefon', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Titula', models.CharField(max_length=50)),
                ('NaKoeOddelenie', models.CharField(max_length=50)),
                ('PoleSpecijalizacija', models.CharField(max_length=50)),
                ('Redoven', models.BooleanField()),
                ('Specijalist', models.BooleanField()),
                ('Faksimil', models.IntegerField(unique=True)),
                ('GodiniIskustvo', models.IntegerField()),
                ('Plata', models.IntegerField()),
                ('Rakovoditel', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Oddeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=50)),
                ('Kapacitet', models.IntegerField()),
                ('PomosenPersonal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pacienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=50)),
                ('Prezime', models.CharField(max_length=50)),
                ('Telefon', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('DataRaganje', models.DateField()),
                ('EMBG', models.CharField(max_length=50, unique=True)),
                ('Pol', models.CharField(max_length=10)),
                ('Krvodaritel', models.BooleanField()),
                ('KrvnaGrupa', models.CharField(max_length=10)),
                ('Osiguruvanje', models.BooleanField()),
                ('Hronicni', models.BooleanField()),
                ('Alergii', models.BooleanField()),
                ('HronicniBolesti', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregledi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatumPregled', models.DateTimeField()),
                ('Zabeleska', models.TextField(blank=True, null=True)),
                ('KontrolaZa', models.IntegerField(blank=True, null=True)),
                ('Dijagnoza', models.TextField(blank=True, null=True)),
                ('Terapija', models.TextField(blank=True, null=True)),
                ('Doktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doktori')),
                ('NaKoeOddelenie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oddeli')),
                ('Pacient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pacienti')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalizacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataHospitalizacija', models.DateField()),
                ('Dijagnoza', models.TextField(blank=True, null=True)),
                ('Rezultati', models.TextField(blank=True, null=True)),
                ('BrSoba', models.IntegerField(blank=True, null=True)),
                ('BrojKrevet', models.IntegerField(blank=True, null=True)),
                ('Terapija', models.CharField(blank=True, max_length=50, null=True)),
                ('Hospitaliziran', models.BooleanField()),
                ('Doktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doktori')),
                ('Oddel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oddeli')),
                ('Pacient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pacienti')),
            ],
        ),
    ]
