# Generated by Django 4.0.4 on 2022-05-11 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Termin', models.DateTimeField()),
                ('Simptomi', models.TextField(blank=True, null=True)),
                ('Prioritet', models.BooleanField(default=False)),
                ('Doktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doktori')),
                ('Oddel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oddeli')),
                ('Pacient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pacienti')),
            ],
        ),
        migrations.AddField(
            model_name='pregledi',
            name='Upat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.termin'),
        ),
    ]
